M48
; DRILL file {KiCad 9.0.7} date 2026-02-02T17:13:08+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-02T17:13:08+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X73.0Y-41.0
X73.0Y-73.15
X79.9Y-92.0
X93.0Y-54.2
X93.0Y-81.35
T2
X74.0Y-34.0
X74.0Y-90.0
X92.0Y-34.114
X92.0Y-90.0
M30
